### ISSUE TITLE
random batching memory issue for large number of training sequences

### ISSUE THREAD

**Issue by ivanjayapurna** [ElArkk/jax-unirep#52] opened 2020-06-09 17:03 UTC
When attempting to evotune (random_batching) I've confirmed the batching works, and runs fine on sub 1000 sequence training sets, but run into "RuntimeError: Resource exhausted: Out of memory" during the training loop. Could be the same issue as the possible memory leak issue #45 .

**Comment by ericmjl** [comment] 2020-06-10 11:01
Looks related to #44 as well. I think we can take the code block at the bottom and stick it into the code base.

**Comment by ElArkk** [comment] 2020-06-10 11:56
I had this code block in mind as well @ericmjl. Would you call it after every iteration or at more sparse intervals?

**Comment by ericmjl** [comment] 2020-06-10 11:58
Every iteration would incur quite a bit of overhead. I think a 10 iteration interval might be the right balance empirically-speaking. Sounds like one of those things that should be configurable with a sane default in place.

**Comment by ElArkk** [comment] 2020-06-15 14:17
Hey @ivanjayapurna , thanks for testing that out! I have stumbled upon another issue in the `jax` repo which might be relevant:

https://github.com/google/jax/issues/2072

There, instead of clearing all memory, they clear cache. I'm not sure though if this is applicable to our problem.

Regarding moving stuff out of the `fit` function. I'm not sure what you mean by `get_reps` here, because this function is not used in `fit`. Do you mean just the embedding step? Taking out the generation of `xs` and `ys` could be worth a try!

**Comment by ericmjl** [comment] 2020-06-15 14:50
@ivanjayapurna do you have a colab file available as well? It'll help me with debugging.

**Comment by ivanjayapurna** [comment] 2020-06-15 16:53
@ElArkk I tried clearing the cache, it didn't solve the memory issue.

For the splitting of the fit functions yes, I was thinking something like you call 1 function to get reps and batch into xs and ys, then you save those. Then you can safely clear all memory, then call another function (modified fit) that loads in the xs and ys and fits to them. If the memory leak is from the generation of xs and ys this should solve the issue, however, if the memory leak is from the new random batching method that occurs in the training loop:
        logging.debug("Getting batches")
        l = choice(seq_lens)
        x, y = len_batching_funcs[l]()
then I don't think this change will make any difference, other than saving time if a user wants to fit multiple times with different hyperparameters on the same dataset (generating xs and ys takes a long time).

@ericmjl  the modifications I've made so far are on here https://github.com/ivanjayapurna/jax-unirep for debugging this. I'll share access to my colab file to your email address.

**Comment by ericmjl** [comment] 2020-08-11 18:28
I think we've made some progress with memory issues. I'm going to close this issue for the time being. Let's start a new thread if anything new shows up.

**Closed by ericmjl** 2020-08-11 18:28 UTC

**Comment by mengqvist** [comment] 2020-09-28 13:32
I get memory issues when running the fit() function as well. I'm using 120 000 sequences with an average length of 241 amino acids. I'm using a batch size of 32, tried both random and length batching. Otherwise settings as in the example you provided. 

```
RuntimeError: Resource exhausted: Out of memory while trying to allocate 14440000 bytes.
```

Possibly related is the logfile entry below. Seems that it concatenates the sequences or something.

```
2020-09-28 15:19:36,734 :: INFO :: Length-batching done: 1 unique lengths, with average length 55530.0, max length 55530 and min length 55530.
```

**Comment by ericmjl** [comment] 2020-09-28 23:08
Ahhh, yes. Preallocation of memory happens, and with a length of 55530, that's a very long protein! I think the UniRep authors were training against proteins of max length 2,000. Most of the enzymes we encounter are on the hundreds of a.a. as well. 

From practical experience handling the model, a combination of batch size and max length give us the memory allocation. I think length 2000 tops out at batch size 22 on an 8GB GTX1080 GPU. Length 1000 possibly will top out at batch size 50-ish. These aren't documented hard rules, though, because I've only had anecdotal experience at the bounds of memory allocation.

**Comment by mengqvist** [comment] 2020-09-29 09:27
My sequences are of average length 421, so there's something weird going on. Even with your mock data from the example I have:
```
>>> sequences
['HASTA',
 'VISTA',
 'ALAVA',
 'LIMED',
 'HAST',
 'HAS',
 'HASVASTA',
 'HASTA',
 'VISTA',
 'ALAVA',
 'LIMED',
 'HAST',
 'HAS',
 'HASVASTA',
 'HASTA',
 'VISTA',
 'ALAVA',
 'LIMED',
 'HAST',
 'HAS',
 'HASVASTA',
 'HASTA',
 'VISTA',
 'ALAVA',
 'LIMED',
 'HAST',
 'HAS',
 'HASVASTA',
 'HASTA',
 'VISTA',
 'ALAVA',
 'LIMED',
 'HAST',
 'HAS',
 'HASVASTA']
```

BUT when I do the evotuning I get the following in the log file:
```
2020-09-29 11:21:50,617 :: INFO :: Length-batching done: 1 unique lengths, with average length 35.0, max length 35 and min length 35.
```

**Comment by ericmjl** [comment] 2020-09-29 12:30
The line in which the logging happens is [here](https://github.com/ElArkk/jax-unirep/blob/master/jax_unirep/evotuning.py#L271). Your output indicates to me something is wonky with the logging, though it'll be probably next week before I can get to the root cause (I have other things planned in my day job).

As for the memory issues, what is the length of the longest sequence that you have? Average sequence length isn't the determinant of maximum memory that needs to be pre-allocated, the maximum sequence length of a given batch is what determines memory prellocation; also, with length batching, every unique sequence length gets memory allocated, so if there's a lot of unique sequence lengths, then there'll be issues with memory there. Could you try the following two things simultaneously?

1. Filter sequences to maximum length 500.
2. Use random batching with batch size 25 first.

Using random batching means we pad all sequences to the maximum length of sequences inside the set using a `-` character. This allows JAX to preallocate just one chunk of memory that fits a sequence length of 500 for 25 sequences, rather than multiple chunks of memory. (It won't be exactly a rectangle matrix for which memory gets preallocated, but more like a 3D tensor behind-the-scenes, IIRC.)

**Comment by ericmjl** [comment] 2020-09-29 12:32
@ElArkk now that we've had this example of how length batching happens in the wild, I think it's a good idea to deprecate it. The idea was good when we had small artisanal batches of data, but seems like the idea might break down when really trying to operate at scale. What are your thoughts?

**Comment by ivanjayapurna** [comment] 2020-09-29 16:34
@mengqvist So the logging output here is kind of confusing, because when you use random batching its not the most useful as its sort of an artifact from the length batching implementation / byproduct of the fact that when you random batch whats actually happening is you pad all your sequences to the same length (== the maximum length of the sequences provided).

By the log output saying there is 1 unique length - all its saying is every sequence is padded to the same length, and by saying avg, min, and max lengths are 35 - its saying that not the sequence lengths are 35, but rather the length of your single batch is of length is 35 - i.e. there are 35 sequences that were padded to the same length (which is the total number of sequences inputted in that toy example).

In your case with using 120,000 sequences, are you sure that data set isn't actually of size 55,530?

In any case as @ericmjl stated above if one of your sequences in the 55,530 or 120,000 is absurdly long, then all your sequences will be padded to be absurdly long - which will be why you are running out of memory, so filtering out any sequences over length 500 AA's should hopefully solve your problem.

**Comment by ElArkk** [comment] 2020-09-29 18:54
@ivanjayapurna iI think you're right, it's very confusing to see the length-batching statement when using random-batching. We should make that print only when length-batching is being used. 

@ericmjl Actually to me, the way we got `fit` working right now, length-batching makes more sense in most cases than random-batching. But maybe I'm missing the point of your comment here, are you saying that it makes a difference memory wise whether we have just one entry in `len_batching_funcs` with all padded sequences (in the case of random-batching) or many smaller entries with the non-padded sequences (length-batching)? If that's the case, should we think about a fast way of sampling seq's without any pre-allocation?

I'm asking this because I fail to see the advantage of random-batching under the current regimen, where we anyways only use one batch of sequences at each update step before choosing a new length. 

In random batching, this just corresponds to getting one random batch out of all sequences, since there's only one length due to padding. In length-batching on the other hand, we choose a different length at each iteration and get non-padded sequences.

The only reason to use random-batching that I can see, is if you have only a few sequences of any given length in your set, and want to use a large `batch_size`.

**Comment by ericmjl** [comment] 2020-09-30 14:01
> @ericmjl Actually to me, the way we got fit working right now, length-batching makes more sense in most cases than random-batching. But maybe I'm missing the point of your comment here, are you saying that it makes a difference memory wise whether we have just one entry in len_batching_funcs with all padded sequences (in the case of random-batching) or many smaller entries with the non-padded sequences (length-batching)? If that's the case, should we think about a fast way of sampling seq's without any pre-allocation?

You're right, I was blanking on how the internals of length-batching was happening when I wrote my comment above. (Working with you on this is always a joy, especially when you catch my errors!) Regardless of length or random batching, pre-allocation of memory happens only for that length batch.

Pivoting a bit, I think it's about time we added in the ability to use the UniRep256 model. "Most powerful model" and "best accuracy" usually don't override the need for usability + "good enough" from an engineering perspective, and I think the 256-dim model might offer a bit more accessibility to the model. (I'm also fascinated by how small we can go in models, but that's another story.) 

Once my power gets restored here (I'm using phone hotspot + batteries, batteries, batteries to stay productive haha), I'll kickstart a new branch with UniRep 256, and try to make it flexible that we can do UniRep-N :smile:.

**Comment by ericmjl** [comment] 2020-09-30 14:13
Thanks too, @ivanjayapurna for chiming in - you've been helpful up here on the issue tracker too!

**Comment by mengqvist** [comment] 2020-10-01 11:45
> The line in which the logging happens is [here](https://github.com/ElArkk/jax-unirep/blob/master/jax_unirep/evotuning.py#L271). Your output indicates to me something is wonky with the logging, when we have a length batch with only 1 sequence, though it'll be probably next week before I can get to the root cause (I have other things planned in my day job).
> 
> As for the memory issues, what is the length of the longest sequence that you have? Average sequence length isn't the determinant of maximum memory that needs to be pre-allocated, the maximum sequence length of a given batch is what determines memory prellocation; also, with length batching, every unique sequence length gets memory allocated, so if there's a lot of unique sequence lengths, then there'll be issues with memory there. Could you try the following two things simultaneously?
> 
>     1. Filter sequences to maximum length 500.
> 
>     2. Use random batching with batch size 25 first.
> 
> 
> Using random batching means we pad all sequences to the maximum length of sequences inside the set using a `-` character. This allows JAX to preallocate just one chunk of memory that fits a sequence length of 500 for 25 sequences, rather than multiple chunks of memory. (It won't be exactly a rectangle matrix for which memory gets preallocated, but more like a 3D tensor behind-the-scenes, IIRC.)

The maximum sequence length is 350, so no need to filter for length. Decreasing the batch size from 32 to 25 worked, however. I can now get the evotuning working, both with length and random batching, on a NVIDIA RTX 2080 (8 GB). Based on the somewhat cryptic logfile entry I assumed a more fundamental problem and therefore did not proceed with trying out different batch sizes. 

@ivanjayapurna 
Many thanks for explaining what the logfile entry means. I am still rather uneasy with the output that it gives. In my latest run with length batching I get:

Which is again very puzzling. My longest sequence is 350 and my shortest is 24. So why would it print out 1854 and 1? It makes me very uneasy.

**Comment by mengqvist** [comment] 2020-10-01 11:51
@ericmjl @ivanjayapurna @ElArkk 
Using your example sequences:
```
>>> sequences = ["HASTA", "VISTA", "ALAVA", "LIMED", "HAST", "HAS", "HASVASTA"] * 5
>>> min([len(s) for s in set(sequences)])
3
>>> max([len(s) for s in set(sequences)])
8
```
Yet in the logfile (running **length** batching in the `fit()` function I see:
```
2020-10-01 13:47:50,785 :: INFO :: Length-batching done: 4 unique lengths, with average length 8.75, max length 20 and min length 5.
```
Which is clearly wrong. Or am I still not getting what the printout means?

**Comment by ivanjayapurna** [comment] 2020-10-01 17:40
Yup, @ElArkk  @ericmjl we should definitely change that log print, its definitely confusing. 1.) should only log that line if length-batching is used
2.) it should be reworded to something like:

2020-10-01 13:39:53,844 :: INFO :: Length-batching done: 318 unique lengths (i.e. batches), with average batch size 349.24528301886795, max batch size 1854 and min batch size 1.

It may also be useful to log the actual sequence length statistics, especially for random batching so users can see if they're running into memory issues because they're padding all their sequences to length >1000 residues.

**Comment by ericmjl** [comment] 2020-10-02 01:29
Thanks @ivanjayapurna, and thanks @mengqvist for chiming in here. This was a user-interface issue that I should have caught earlier, but I guess being overly-familiar with the project puts me in a position with many blind spots.

Because this issue has been closed, I'm going to raise another one that is on-topic, so we can keep track of progress.

**Comment by mengqvist** [comment] 2020-10-05 07:29
@ElArkk 
> I'm asking this because I fail to see the advantage of random-batching under the current regimen, where we anyways only use one batch of sequences at each update step before choosing a new length.
>
>In random batching, this just corresponds to getting one random batch out of all sequences, since there's only one length due to padding. In length-batching on the other hand, we choose a different length at each iteration and get non-padded sequences.
>
>The only reason to use random-batching that I can see, is if you have only a few sequences of any given length in your set, and want to use a large batch_size.

I ran some tests using my set of 100 k sequences and I get better results with random batching. My suspicion is that this is due to the sequences being quite similar. So when you do length batching you probably get groups of sequences that are very similar, since in a set of similar sequences the ones with the same length will presumably have tended to diverge less than those of different lengths. The gradients obtained in each batch may therefore be quite different. So it maybe random batching is trickier on the memory side, but it is my preferred setting for evotuning. But then again, it might be highly dependent on which protein family you're working with. (as a side note these are the losses reported in the logfile, couldn't quite figure out how to get the loss in each epoch directly)

![image](https://user-images.githubusercontent.com/5589982/95050858-8d716700-06ec-11eb-92c8-1104fae7d1be.png)

**Comment by ElArkk** [comment] 2020-10-05 14:55
@mengqvist that's a very cool observation, I didn't think about this aspect of similarity of batched sequences! We should definitely document this to make users aware.
