### ISSUE TITLE
Error when using get_reps with evotuned params

### ISSUE THREAD

**Issue by rushabh31** [ElArkk/jax-unirep#108] opened 2021-03-25 15:30 UTC
First of all, Thank you very much for such a wonderful library. I am trying to `evotune`  using my own sequences and trying to get the representation for visualization purposes. 
I am using below code:

```
from pathlib import Path
from jax.random import PRNGKey
from jax_unirep import evotune
from jax_unirep import fit
from jax_unirep.evotuning_models import mlstm1900
from jax_unirep.utils import dump_params
import pandas as pd
from jax_unirep.utils import load_params
from jax_unirep import get_reps

sequences = ["HASTA", "VISTA", "ALAVA", "LIMED", "HAST", "HAS", "HASVASTA"] * 5
holdout_sequences = ["HASTA",  "VISTA", "ALAVA", "LIMED","HAST","HASVALTA"] * 5

# First way: Use the default mLSTM1900 weights with mLSTM1900 model.
"""Evotuning two ways!"""
init_fun, apply_fun = mlstm1900()

# The input_shape is always going to be (-1, 26),
# because that is the number of unique AA, one-hot encoded.
_, inital_params = init_fun(PRNGKey(42), input_shape=(-1, 26))

# 1. Evotuning with Optuna
n_epochs_config = {"low": 1, "high": 1}
lr_config = {"low": 1e-5, "high": 1e-3}
study, evotuned_params = evotune(
    sequences=sequences,
    model_func=apply_fun,
    params=inital_params,
    out_dom_seqs=holdout_sequences,
    n_trials=2,
    n_splits=2,
    n_epochs_config=n_epochs_config,
    learning_rate_config=lr_config,

)

PROJECT_NAME = "evotuning_temp"

dump_params(evotuned_params, Path(PROJECT_NAME))
print("Evotuning done! Find output weights in", PROJECT_NAME)
print(study.trials_dataframe())

data = ["HAST", "VISTA", "ALAVA", "LIMED"]

h_avg, h_final, c_final = get_reps(data,params=evotuned_params,mlstm_size=1900)

```

I am getting the below error when using `evotuned_params` dictionary. I am new to this library and it would be really helpful if you guide me if I am doing anything wrong.

![image](https://user-images.githubusercontent.com/50964981/112498943-5f94e300-8d5d-11eb-9bc7-0ab5f8c654af.png)

**Comment by ElArkk** [comment] 2021-03-31 11:52
Hi @rushabh31 

At first glance, I think the problem is that `evotune` returns not only the mLSTM parameters, but also the params of the other layers (embedding, fully connected etc.). `get_reps` on the other hand expects only the mLSTm params. try switching out your last line with the following:

```python
h_avg, h_final, c_final = get_reps(data, params=evotuned_params[1], mlstm_size=1900)
```

**Comment by ericmjl** [comment] 2021-05-09 13:56
Closing this issue for the time being.

**Closed by ericmjl** 2021-05-09 13:56 UTC
